import React from 'react';
//import * from 'fs';
//import * from 'path';

const svgContent : string = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.40.1 (20161225.0304)
 -->
<!-- Title: CNTKGraph Pages: 1 -->
<svg width="6583pt" height="330pt"
 viewBox="0.00 0.00 6582.84 330.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 326)">
<title>CNTKGraph</title>
<polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-326 6578.841,-326 6578.841,4 -4,4"/>
<!-- Times212_reshape1/Reshape (op#0)\n input0 Parameter193\n input1 Parameter193_reshape1_shape\n output0 Parameter193_reshape1 -->
<g id="node1" class="node">
<title>Times212_reshape1/Reshape (op#0)\n input0 Parameter193\n input1 Parameter193_reshape1_shape\n output0 Parameter193_reshape1</title>
<polygon fill="#0f9d58" stroke="#0f9d58" points="5067.341,-98 4770.341,-98 4770.341,-30 5067.341,-30 5067.341,-98"/>
<text text-anchor="middle" x="4918.841" y="-82.8" font-family="Times,serif" font-size="14.00" fill="#ffffff">Times212_reshape1/Reshape (op#0)</text>
<text text-anchor="middle" x="4918.841" y="-67.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input0 Parameter193</text>
<text text-anchor="middle" x="4918.841" y="-52.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input1 Parameter193_reshape1_shape</text>
<text text-anchor="middle" x="4918.841" y="-37.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> output0 Parameter193_reshape1</text>
</g>
<!-- Parameter193_reshape10 -->
<g id="node2" class="node">
<title>Parameter193_reshape10</title>
<polygon fill="none" stroke="#000000" points="5437.4822,-72.5442 5437.4822,-87.4558 5358.3183,-98 5246.3637,-98 5167.1999,-87.4558 5167.1999,-72.5442 5246.3637,-62 5358.3183,-62 5437.4822,-72.5442"/>
<text text-anchor="middle" x="5302.341" y="-76.3" font-family="Times,serif" font-size="14.00" fill="#000000">Parameter193_reshape1</text>
</g>
<!-- Times212_reshape1/Reshape (op#0)\n input0 Parameter193\n input1 Parameter193_reshape1_shape\n output0 Parameter193_reshape1&#45;&gt;Parameter193_reshape10 -->
<g id="edge1" class="edge">
<title>Times212_reshape1/Reshape (op#0)\n input0 Parameter193\n input1 Parameter193_reshape1_shape\n output0 Parameter193_reshape1&#45;&gt;Parameter193_reshape10</title>
<path fill="none" stroke="#000000" d="M5067.3866,-70.1975C5096.7836,-71.4239 5127.6097,-72.71 5156.9021,-73.9321"/>
<polygon fill="#000000" stroke="#000000" points="5157.0572,-77.4416 5167.1944,-74.3615 5157.349,-70.4476 5157.0572,-77.4416"/>
</g>
<!-- Times212/MatMul (op#10)\n input0 Pooling160_Output_0_reshape0\n input1 Parameter193_reshape1\n output0 Times212_Output_0 -->
<g id="node5" class="node">
<title>Times212/MatMul (op#10)\n input0 Pooling160_Output_0_reshape0\n input1 Parameter193_reshape1\n output0 Times212_Output_0</title>
<polygon fill="#0f9d58" stroke="#0f9d58" points="5810.841,-141 5510.841,-141 5510.841,-73 5810.841,-73 5810.841,-141"/>
<text text-anchor="middle" x="5660.841" y="-125.8" font-family="Times,serif" font-size="14.00" fill="#ffffff">Times212/MatMul (op#10)</text>
<text text-anchor="middle" x="5660.841" y="-110.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input0 Pooling160_Output_0_reshape0</text>
<text text-anchor="middle" x="5660.841" y="-95.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input1 Parameter193_reshape1</text>
<text text-anchor="middle" x="5660.841" y="-80.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> output0 Times212_Output_0</text>
</g>
<!-- Parameter193_reshape10&#45;&gt;Times212/MatMul (op#10)\n input0 Pooling160_Output_0_reshape0\n input1 Parameter193_reshape1\n output0 Times212_Output_0 -->
<g id="edge4" class="edge">
<title>Parameter193_reshape10&#45;&gt;Times212/MatMul (op#10)\n input0 Pooling160_Output_0_reshape0\n input1 Parameter193_reshape1\n output0 Times212_Output_0</title>
<path fill="none" stroke="#000000" d="M5424.4633,-89.1975C5448.9153,-91.0391 5474.9512,-92.9999 5500.471,-94.9219"/>
<polygon fill="#000000" stroke="#000000" points="5500.3668,-98.4239 5510.6015,-95.6849 5500.8926,-91.4437 5500.3668,-98.4239"/>
</g>
<!-- Parameter1930 -->
<g id="node3" class="node">
<title>Parameter1930</title>
<polygon fill="none" stroke="#000000" points="4584.7728,-64.5442 4584.7728,-79.4558 4535.6067,-90 4466.0754,-90 4416.9093,-79.4558 4416.9093,-64.5442 4466.0754,-54 4535.6067,-54 4584.7728,-64.5442"/>
<text text-anchor="middle" x="4500.841" y="-68.3" font-family="Times,serif" font-size="14.00" fill="#000000">Parameter193</text>
</g>
<!-- Parameter1930&#45;&gt;Times212_reshape1/Reshape (op#0)\n input0 Parameter193\n input1 Parameter193_reshape1_shape\n output0 Parameter193_reshape1 -->
<g id="edge2" class="edge">
<title>Parameter1930&#45;&gt;Times212_reshape1/Reshape (op#0)\n input0 Parameter193\n input1 Parameter193_reshape1_shape\n output0 Parameter193_reshape1</title>
<path fill="none" stroke="#000000" d="M4584.6757,-70.3955C4634.8034,-69.4361 4700.1397,-68.1857 4759.7294,-67.0452"/>
<polygon fill="#000000" stroke="#000000" points="4760.0785,-70.5393 4770.0096,-66.8484 4759.9444,-63.5405 4760.0785,-70.5393"/>
</g>
<!-- Parameter193_reshape1_shape0 -->
<g id="node4" class="node">
<title>Parameter193_reshape1_shape0</title>
<polygon fill="none" stroke="#000000" points="4671.3318,-10.5442 4671.3318,-25.4558 4571.4606,-36 4430.2215,-36 4330.3503,-25.4558 4330.3503,-10.5442 4430.2215,0 4571.4606,0 4671.3318,-10.5442"/>
<text text-anchor="middle" x="4500.841" y="-14.3" font-family="Times,serif" font-size="14.00" fill="#000000">Parameter193_reshape1_shape</text>
</g>
<!-- Parameter193_reshape1_shape0&#45;&gt;Times212_reshape1/Reshape (op#0)\n input0 Parameter193\n input1 Parameter193_reshape1_shape\n output0 Parameter193_reshape1 -->
<g id="edge3" class="edge">
<title>Parameter193_reshape1_shape0&#45;&gt;Times212_reshape1/Reshape (op#0)\n input0 Parameter193\n input1 Parameter193_reshape1_shape\n output0 Parameter193_reshape1</title>
<path fill="none" stroke="#000000" d="M4618.947,-30.9973C4662.7851,-35.8216 4713.2493,-41.3751 4760.1256,-46.5337"/>
<polygon fill="#000000" stroke="#000000" points="4759.7474,-50.0131 4770.0703,-47.6281 4760.5132,-43.0551 4759.7474,-50.0131"/>
</g>
<!-- Times212_Output_00 -->
<g id="node30" class="node">
<title>Times212_Output_00</title>
<polygon fill="none" stroke="#000000" points="6074.841,-99.5442 6074.841,-114.4558 6008.0614,-125 5913.6207,-125 5846.841,-114.4558 5846.841,-99.5442 5913.6207,-89 6008.0614,-89 6074.841,-99.5442"/>
<text text-anchor="middle" x="5960.841" y="-103.3" font-family="Times,serif" font-size="14.00" fill="#000000">Times212_Output_0</text>
</g>
<!-- Times212/MatMul (op#10)\n input0 Pooling160_Output_0_reshape0\n input1 Parameter193_reshape1\n output0 Times212_Output_0&#45;&gt;Times212_Output_00 -->
<g id="edge29" class="edge">
<title>Times212/MatMul (op#10)\n input0 Pooling160_Output_0_reshape0\n input1 Parameter193_reshape1\n output0 Times212_Output_0&#45;&gt;Times212_Output_00</title>
<path fill="none" stroke="#000000" d="M5810.841,-107C5819.3806,-107 5827.9202,-107 5836.3491,-107"/>
<polygon fill="#000000" stroke="#000000" points="5836.5681,-110.5001 5846.5681,-107 5836.5681,-103.5001 5836.5681,-110.5001"/>
</g>
<!-- Convolution28/Conv (op#1)\n input0 Input3\n input1 Parameter5\n output0 Convolution28_Output_0 -->
<g id="node6" class="node">
<title>Convolution28/Conv (op#1)\n input0 Input3\n input1 Parameter5\n output0 Convolution28_Output_0</title>
<polygon fill="#0f9d58" stroke="#0f9d58" points="439.1055,-311 178.1055,-311 178.1055,-243 439.1055,-243 439.1055,-311"/>
<text text-anchor="middle" x="308.6055" y="-295.8" font-family="Times,serif" font-size="14.00" fill="#ffffff">Convolution28/Conv (op#1)</text>
<text text-anchor="middle" x="308.6055" y="-280.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input0 Input3</text>
<text text-anchor="middle" x="308.6055" y="-265.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input1 Parameter5</text>
<text text-anchor="middle" x="308.6055" y="-250.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> output0 Convolution28_Output_0</text>
</g>
<!-- Convolution28_Output_00 -->
<g id="node7" class="node">
<title>Convolution28_Output_00</title>
<polygon fill="none" stroke="#000000" points="751.1055,-269.5442 751.1055,-284.4558 670.267,-295 555.944,-295 475.1055,-284.4558 475.1055,-269.5442 555.944,-259 670.267,-259 751.1055,-269.5442"/>
<text text-anchor="middle" x="613.1055" y="-273.3" font-family="Times,serif" font-size="14.00" fill="#000000">Convolution28_Output_0</text>
</g>
<!-- Convolution28/Conv (op#1)\n input0 Input3\n input1 Parameter5\n output0 Convolution28_Output_0&#45;&gt;Convolution28_Output_00 -->
<g id="edge5" class="edge">
<title>Convolution28/Conv (op#1)\n input0 Input3\n input1 Parameter5\n output0 Convolution28_Output_0&#45;&gt;Convolution28_Output_00</title>
<path fill="none" stroke="#000000" d="M439.5081,-277C447.8736,-277 456.3269,-277 464.7642,-277"/>
<polygon fill="#000000" stroke="#000000" points="465.0409,-280.5001 475.0409,-277 465.0409,-273.5001 465.0409,-280.5001"/>
</g>
<!-- Plus30/Add (op#2)\n input0 Convolution28_Output_0\n input1 Parameter6\n output0 Plus30_Output_0 -->
<g id="node10" class="node">
<title>Plus30/Add (op#2)\n input0 Convolution28_Output_0\n input1 Parameter6\n output0 Plus30_Output_0</title>
<polygon fill="#0f9d58" stroke="#0f9d58" points="1038.1055,-284 787.1055,-284 787.1055,-216 1038.1055,-216 1038.1055,-284"/>
<text text-anchor="middle" x="912.6055" y="-268.8" font-family="Times,serif" font-size="14.00" fill="#ffffff">Plus30/Add (op#2)</text>
<text text-anchor="middle" x="912.6055" y="-253.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input0 Convolution28_Output_0</text>
<text text-anchor="middle" x="912.6055" y="-238.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input1 Parameter6</text>
<text text-anchor="middle" x="912.6055" y="-223.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> output0 Plus30_Output_0</text>
</g>
<!-- Convolution28_Output_00&#45;&gt;Plus30/Add (op#2)\n input0 Convolution28_Output_0\n input1 Parameter6\n output0 Plus30_Output_0 -->
<g id="edge8" class="edge">
<title>Convolution28_Output_00&#45;&gt;Plus30/Add (op#2)\n input0 Convolution28_Output_0\n input1 Parameter6\n output0 Plus30_Output_0</title>
<path fill="none" stroke="#000000" d="M728.9,-266.5611C744.4284,-265.1612 760.4711,-263.715 776.3113,-262.287"/>
<polygon fill="#000000" stroke="#000000" points="777.0386,-265.7357 786.6839,-261.3519 776.41,-258.7639 777.0386,-265.7357"/>
</g>
<!-- Input30 -->
<g id="node8" class="node">
<title>Input30</title>
<polygon fill="none" stroke="#000000" points="117.0079,-296.5442 117.0079,-311.4558 90.088,-322 52.0175,-322 25.0976,-311.4558 25.0976,-296.5442 52.0175,-286 90.088,-286 117.0079,-296.5442"/>
<text text-anchor="middle" x="71.0527" y="-300.3" font-family="Times,serif" font-size="14.00" fill="#000000">Input3</text>
</g>
<!-- Input30&#45;&gt;Convolution28/Conv (op#1)\n input0 Input3\n input1 Parameter5\n output0 Convolution28_Output_0 -->
<g id="edge6" class="edge">
<title>Input30&#45;&gt;Convolution28/Conv (op#1)\n input0 Input3\n input1 Parameter5\n output0 Convolution28_Output_0</title>
<path fill="none" stroke="#000000" d="M116.8553,-298.7941C131.9409,-297.0795 149.5906,-295.0735 167.9633,-292.9852"/>
<polygon fill="#000000" stroke="#000000" points="168.3879,-296.4596 177.9287,-291.8526 167.5973,-289.5044 168.3879,-296.4596"/>
</g>
<!-- Parameter50 -->
<g id="node9" class="node">
<title>Parameter50</title>
<polygon fill="none" stroke="#000000" points="142.1583,-242.5442 142.1583,-257.4558 100.5056,-268 41.5999,-268 -.0528,-257.4558 -.0528,-242.5442 41.5999,-232 100.5056,-232 142.1583,-242.5442"/>
<text text-anchor="middle" x="71.0527" y="-246.3" font-family="Times,serif" font-size="14.00" fill="#000000">Parameter5</text>
</g>
<!-- Parameter50&#45;&gt;Convolution28/Conv (op#1)\n input0 Input3\n input1 Parameter5\n output0 Convolution28_Output_0 -->
<g id="edge7" class="edge">
<title>Parameter50&#45;&gt;Convolution28/Conv (op#1)\n input0 Input3\n input1 Parameter5\n output0 Convolution28_Output_0</title>
<path fill="none" stroke="#000000" d="M140.7213,-257.9185C149.3677,-258.9012 158.4354,-259.9318 167.689,-260.9836"/>
<polygon fill="#000000" stroke="#000000" points="167.4607,-264.4801 177.792,-262.1319 168.2513,-257.5249 167.4607,-264.4801"/>
</g>
<!-- Plus30_Output_00 -->
<g id="node11" class="node">
<title>Plus30_Output_00</title>
<polygon fill="none" stroke="#000000" points="1271.1055,-242.5442 1271.1055,-257.4558 1213.4055,-268 1131.8055,-268 1074.1055,-257.4558 1074.1055,-242.5442 1131.8055,-232 1213.4055,-232 1271.1055,-242.5442"/>
<text text-anchor="middle" x="1172.6055" y="-246.3" font-family="Times,serif" font-size="14.00" fill="#000000">Plus30_Output_0</text>
</g>
<!-- Plus30/Add (op#2)\n input0 Convolution28_Output_0\n input1 Parameter6\n output0 Plus30_Output_0&#45;&gt;Plus30_Output_00 -->
<g id="edge9" class="edge">
<title>Plus30/Add (op#2)\n input0 Convolution28_Output_0\n input1 Parameter6\n output0 Plus30_Output_0&#45;&gt;Plus30_Output_00</title>
<path fill="none" stroke="#000000" d="M1038.4167,-250C1046.8947,-250 1055.3965,-250 1063.7776,-250"/>
<polygon fill="#000000" stroke="#000000" points="1063.9312,-253.5001 1073.9312,-250 1063.9312,-246.5001 1063.9312,-253.5001"/>
</g>
<!-- ReLU32/Relu (op#3)\n input0 Plus30_Output_0\n output0 ReLU32_Output_0 -->
<g id="node13" class="node">
<title>ReLU32/Relu (op#3)\n input0 Plus30_Output_0\n output0 ReLU32_Output_0</title>
<polygon fill="#0f9d58" stroke="#0f9d58" points="1522.1055,-276.5 1307.1055,-276.5 1307.1055,-223.5 1522.1055,-223.5 1522.1055,-276.5"/>
<text text-anchor="middle" x="1414.6055" y="-261.3" font-family="Times,serif" font-size="14.00" fill="#ffffff">ReLU32/Relu (op#3)</text>
<text text-anchor="middle" x="1414.6055" y="-246.3" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input0 Plus30_Output_0</text>
<text text-anchor="middle" x="1414.6055" y="-231.3" font-family="Times,serif" font-size="14.00" fill="#ffffff"> output0 ReLU32_Output_0</text>
</g>
<!-- Plus30_Output_00&#45;&gt;ReLU32/Relu (op#3)\n input0 Plus30_Output_0\n output0 ReLU32_Output_0 -->
<g id="edge11" class="edge">
<title>Plus30_Output_00&#45;&gt;ReLU32/Relu (op#3)\n input0 Plus30_Output_0\n output0 ReLU32_Output_0</title>
<path fill="none" stroke="#000000" d="M1271.3852,-250C1279.8395,-250 1288.4437,-250 1297.0249,-250"/>
<polygon fill="#000000" stroke="#000000" points="1297.0777,-253.5001 1307.0776,-250 1297.0776,-246.5001 1297.0777,-253.5001"/>
</g>
<!-- Parameter60 -->
<g id="node12" class="node">
<title>Parameter60</title>
<polygon fill="none" stroke="#000000" points="684.211,-215.5442 684.211,-230.4558 642.5584,-241 583.6526,-241 542,-230.4558 542,-215.5442 583.6526,-205 642.5584,-205 684.211,-215.5442"/>
<text text-anchor="middle" x="613.1055" y="-219.3" font-family="Times,serif" font-size="14.00" fill="#000000">Parameter6</text>
</g>
<!-- Parameter60&#45;&gt;Plus30/Add (op#2)\n input0 Convolution28_Output_0\n input1 Parameter6\n output0 Plus30_Output_0 -->
<g id="edge10" class="edge">
<title>Parameter60&#45;&gt;Plus30/Add (op#2)\n input0 Convolution28_Output_0\n input1 Parameter6\n output0 Plus30_Output_0</title>
<path fill="none" stroke="#000000" d="M684.4627,-229.4329C712.1745,-231.9311 744.8743,-234.879 776.7295,-237.7507"/>
<polygon fill="#000000" stroke="#000000" points="776.7611,-241.2677 787.035,-238.6798 777.3897,-234.296 776.7611,-241.2677"/>
</g>
<!-- ReLU32_Output_00 -->
<g id="node14" class="node">
<title>ReLU32_Output_00</title>
<polygon fill="none" stroke="#000000" points="1768.1055,-242.5442 1768.1055,-257.4558 1706.5979,-268 1619.6131,-268 1558.1055,-257.4558 1558.1055,-242.5442 1619.6131,-232 1706.5979,-232 1768.1055,-242.5442"/>
<text text-anchor="middle" x="1663.1055" y="-246.3" font-family="Times,serif" font-size="14.00" fill="#000000">ReLU32_Output_0</text>
</g>
<!-- ReLU32/Relu (op#3)\n input0 Plus30_Output_0\n output0 ReLU32_Output_0&#45;&gt;ReLU32_Output_00 -->
<g id="edge12" class="edge">
<title>ReLU32/Relu (op#3)\n input0 Plus30_Output_0\n output0 ReLU32_Output_0&#45;&gt;ReLU32_Output_00</title>
<path fill="none" stroke="#000000" d="M1522.1559,-250C1530.5489,-250 1539.0454,-250 1547.4884,-250"/>
<polygon fill="#000000" stroke="#000000" points="1547.7501,-253.5001 1557.7501,-250 1547.75,-246.5001 1547.7501,-253.5001"/>
</g>
<!-- Pooling66/MaxPool (op#4)\n input0 ReLU32_Output_0\n output0 Pooling66_Output_0 -->
<g id="node15" class="node">
<title>Pooling66/MaxPool (op#4)\n input0 ReLU32_Output_0\n output0 Pooling66_Output_0</title>
<polygon fill="#0f9d58" stroke="#0f9d58" points="2031.1055,-276.5 1804.1055,-276.5 1804.1055,-223.5 2031.1055,-223.5 2031.1055,-276.5"/>
<text text-anchor="middle" x="1917.6055" y="-261.3" font-family="Times,serif" font-size="14.00" fill="#ffffff">Pooling66/MaxPool (op#4)</text>
<text text-anchor="middle" x="1917.6055" y="-246.3" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input0 ReLU32_Output_0</text>
<text text-anchor="middle" x="1917.6055" y="-231.3" font-family="Times,serif" font-size="14.00" fill="#ffffff"> output0 Pooling66_Output_0</text>
</g>
<!-- ReLU32_Output_00&#45;&gt;Pooling66/MaxPool (op#4)\n input0 ReLU32_Output_0\n output0 Pooling66_Output_0 -->
<g id="edge13" class="edge">
<title>ReLU32_Output_00&#45;&gt;Pooling66/MaxPool (op#4)\n input0 ReLU32_Output_0\n output0 Pooling66_Output_0</title>
<path fill="none" stroke="#000000" d="M1768.4575,-250C1776.9102,-250 1785.4958,-250 1794.059,-250"/>
<polygon fill="#000000" stroke="#000000" points="1794.0919,-253.5001 1804.0919,-250 1794.0918,-246.5001 1794.0919,-253.5001"/>
</g>
<!-- Pooling66_Output_00 -->
<g id="node16" class="node">
<title>Pooling66_Output_00</title>
<polygon fill="none" stroke="#000000" points="2295.1055,-242.5442 2295.1055,-257.4558 2228.3258,-268 2133.8851,-268 2067.1055,-257.4558 2067.1055,-242.5442 2133.8851,-232 2228.3258,-232 2295.1055,-242.5442"/>
<text text-anchor="middle" x="2181.1055" y="-246.3" font-family="Times,serif" font-size="14.00" fill="#000000">Pooling66_Output_0</text>
</g>
<!-- Pooling66/MaxPool (op#4)\n input0 ReLU32_Output_0\n output0 Pooling66_Output_0&#45;&gt;Pooling66_Output_00 -->
<g id="edge14" class="edge">
<title>Pooling66/MaxPool (op#4)\n input0 ReLU32_Output_0\n output0 Pooling66_Output_0&#45;&gt;Pooling66_Output_00</title>
<path fill="none" stroke="#000000" d="M2031.2651,-250C2039.7748,-250 2048.3871,-250 2056.9564,-250"/>
<polygon fill="#000000" stroke="#000000" points="2056.9876,-253.5001 2066.9876,-250 2056.9875,-246.5001 2056.9876,-253.5001"/>
</g>
<!-- Convolution110/Conv (op#5)\n input0 Pooling66_Output_0\n input1 Parameter87\n output0 Convolution110_Output_0 -->
<g id="node17" class="node">
<title>Convolution110/Conv (op#5)\n input0 Pooling66_Output_0\n input1 Parameter87\n output0 Convolution110_Output_0</title>
<polygon fill="#0f9d58" stroke="#0f9d58" points="2601.1055,-257 2331.1055,-257 2331.1055,-189 2601.1055,-189 2601.1055,-257"/>
<text text-anchor="middle" x="2466.1055" y="-241.8" font-family="Times,serif" font-size="14.00" fill="#ffffff">Convolution110/Conv (op#5)</text>
<text text-anchor="middle" x="2466.1055" y="-226.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input0 Pooling66_Output_0</text>
<text text-anchor="middle" x="2466.1055" y="-211.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input1 Parameter87</text>
<text text-anchor="middle" x="2466.1055" y="-196.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> output0 Convolution110_Output_0</text>
</g>
<!-- Pooling66_Output_00&#45;&gt;Convolution110/Conv (op#5)\n input0 Pooling66_Output_0\n input1 Parameter87\n output0 Convolution110_Output_0 -->
<g id="edge15" class="edge">
<title>Pooling66_Output_00&#45;&gt;Convolution110/Conv (op#5)\n input0 Pooling66_Output_0\n input1 Parameter87\n output0 Convolution110_Output_0</title>
<path fill="none" stroke="#000000" d="M2281.9869,-240.4428C2294.6195,-239.246 2307.7305,-238.004 2320.8724,-236.7589"/>
<polygon fill="#000000" stroke="#000000" points="2321.2955,-240.2346 2330.9208,-235.807 2320.6352,-233.2658 2321.2955,-240.2346"/>
</g>
<!-- Convolution110_Output_00 -->
<g id="node18" class="node">
<title>Convolution110_Output_00</title>
<polygon fill="none" stroke="#000000" points="2925.7537,-215.5442 2925.7537,-230.4558 2841.1472,-241 2721.4957,-241 2636.8892,-230.4558 2636.8892,-215.5442 2721.4957,-205 2841.1472,-205 2925.7537,-215.5442"/>
<text text-anchor="middle" x="2781.3215" y="-219.3" font-family="Times,serif" font-size="14.00" fill="#000000">Convolution110_Output_0</text>
</g>
<!-- Convolution110/Conv (op#5)\n input0 Pooling66_Output_0\n input1 Parameter87\n output0 Convolution110_Output_0&#45;&gt;Convolution110_Output_00 -->
<g id="edge16" class="edge">
<title>Convolution110/Conv (op#5)\n input0 Pooling66_Output_0\n input1 Parameter87\n output0 Convolution110_Output_0&#45;&gt;Convolution110_Output_00</title>
<path fill="none" stroke="#000000" d="M2601.1572,-223C2609.6845,-223 2618.3017,-223 2626.9063,-223"/>
<polygon fill="#000000" stroke="#000000" points="2626.9953,-226.5001 2636.9953,-223 2626.9952,-219.5001 2626.9953,-226.5001"/>
</g>
<!-- Plus112/Add (op#6)\n input0 Convolution110_Output_0\n input1 Parameter88\n output0 Plus112_Output_0 -->
<g id="node20" class="node">
<title>Plus112/Add (op#6)\n input0 Convolution110_Output_0\n input1 Parameter88\n output0 Plus112_Output_0</title>
<polygon fill="#0f9d58" stroke="#0f9d58" points="3221.5374,-230 2961.5374,-230 2961.5374,-162 3221.5374,-162 3221.5374,-230"/>
<text text-anchor="middle" x="3091.5374" y="-214.8" font-family="Times,serif" font-size="14.00" fill="#ffffff">Plus112/Add (op#6)</text>
<text text-anchor="middle" x="3091.5374" y="-199.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input0 Convolution110_Output_0</text>
<text text-anchor="middle" x="3091.5374" y="-184.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input1 Parameter88</text>
<text text-anchor="middle" x="3091.5374" y="-169.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> output0 Plus112_Output_0</text>
</g>
<!-- Convolution110_Output_00&#45;&gt;Plus112/Add (op#6)\n input0 Convolution110_Output_0\n input1 Parameter88\n output0 Plus112_Output_0 -->
<g id="edge18" class="edge">
<title>Convolution110_Output_00&#45;&gt;Plus112/Add (op#6)\n input0 Convolution110_Output_0\n input1 Parameter88\n output0 Plus112_Output_0</title>
<path fill="none" stroke="#000000" d="M2901.703,-212.5225C2917.9226,-211.1108 2934.6761,-209.6526 2951.2039,-208.2141"/>
<polygon fill="#000000" stroke="#000000" points="2951.7999,-211.6755 2961.4587,-207.3215 2951.1929,-204.7019 2951.7999,-211.6755"/>
</g>
<!-- Parameter870 -->
<g id="node19" class="node">
<title>Parameter870</title>
<polygon fill="none" stroke="#000000" points="2258.6055,-188.5442 2258.6055,-203.4558 2213.207,-214 2149.0039,-214 2103.6055,-203.4558 2103.6055,-188.5442 2149.0039,-178 2213.207,-178 2258.6055,-188.5442"/>
<text text-anchor="middle" x="2181.1055" y="-192.3" font-family="Times,serif" font-size="14.00" fill="#000000">Parameter87</text>
</g>
<!-- Parameter870&#45;&gt;Convolution110/Conv (op#5)\n input0 Pooling66_Output_0\n input1 Parameter87\n output0 Convolution110_Output_0 -->
<g id="edge17" class="edge">
<title>Parameter870&#45;&gt;Convolution110/Conv (op#5)\n input0 Pooling66_Output_0\n input1 Parameter87\n output0 Convolution110_Output_0</title>
<path fill="none" stroke="#000000" d="M2258.6065,-203.3422C2277.9589,-205.1756 2299.3467,-207.2018 2320.819,-209.236"/>
<polygon fill="#000000" stroke="#000000" points="2320.7338,-212.7435 2331.0193,-210.2024 2321.394,-205.7747 2320.7338,-212.7435"/>
</g>
<!-- Plus112_Output_00 -->
<g id="node21" class="node">
<title>Plus112_Output_00</title>
<polygon fill="none" stroke="#000000" points="3467.5374,-188.5442 3467.5374,-203.4558 3406.0298,-214 3319.045,-214 3257.5374,-203.4558 3257.5374,-188.5442 3319.045,-178 3406.0298,-178 3467.5374,-188.5442"/>
<text text-anchor="middle" x="3362.5374" y="-192.3" font-family="Times,serif" font-size="14.00" fill="#000000">Plus112_Output_0</text>
</g>
<!-- Plus112/Add (op#6)\n input0 Convolution110_Output_0\n input1 Parameter88\n output0 Plus112_Output_0&#45;&gt;Plus112_Output_00 -->
<g id="edge19" class="edge">
<title>Plus112/Add (op#6)\n input0 Convolution110_Output_0\n input1 Parameter88\n output0 Plus112_Output_0&#45;&gt;Plus112_Output_00</title>
<path fill="none" stroke="#000000" d="M3221.8779,-196C3230.3611,-196 3238.8714,-196 3247.2754,-196"/>
<polygon fill="#000000" stroke="#000000" points="3247.4648,-199.5001 3257.4648,-196 3247.4648,-192.5001 3247.4648,-199.5001"/>
</g>
<!-- ReLU114/Relu (op#7)\n input0 Plus112_Output_0\n output0 ReLU114_Output_0 -->
<g id="node23" class="node">
<title>ReLU114/Relu (op#7)\n input0 Plus112_Output_0\n output0 ReLU114_Output_0</title>
<polygon fill="#0f9d58" stroke="#0f9d58" points="3727.5374,-222.5 3503.5374,-222.5 3503.5374,-169.5 3727.5374,-169.5 3727.5374,-222.5"/>
<text text-anchor="middle" x="3615.5374" y="-207.3" font-family="Times,serif" font-size="14.00" fill="#ffffff">ReLU114/Relu (op#7)</text>
<text text-anchor="middle" x="3615.5374" y="-192.3" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input0 Plus112_Output_0</text>
<text text-anchor="middle" x="3615.5374" y="-177.3" font-family="Times,serif" font-size="14.00" fill="#ffffff"> output0 ReLU114_Output_0</text>
</g>
<!-- Plus112_Output_00&#45;&gt;ReLU114/Relu (op#7)\n input0 Plus112_Output_0\n output0 ReLU114_Output_0 -->
<g id="edge21" class="edge">
<title>Plus112_Output_00&#45;&gt;ReLU114/Relu (op#7)\n input0 Plus112_Output_0\n output0 ReLU114_Output_0</title>
<path fill="none" stroke="#000000" d="M3467.6342,-196C3476.1238,-196 3484.7458,-196 3493.3412,-196"/>
<polygon fill="#000000" stroke="#000000" points="3493.4099,-199.5001 3503.4098,-196 3493.4098,-192.5001 3493.4099,-199.5001"/>
</g>
<!-- Parameter880 -->
<g id="node22" class="node">
<title>Parameter880</title>
<polygon fill="none" stroke="#000000" points="2858.8215,-161.5442 2858.8215,-176.4558 2813.423,-187 2749.2199,-187 2703.8215,-176.4558 2703.8215,-161.5442 2749.2199,-151 2813.423,-151 2858.8215,-161.5442"/>
<text text-anchor="middle" x="2781.3215" y="-165.3" font-family="Times,serif" font-size="14.00" fill="#000000">Parameter88</text>
</g>
<!-- Parameter880&#45;&gt;Plus112/Add (op#6)\n input0 Convolution110_Output_0\n input1 Parameter88\n output0 Plus112_Output_0 -->
<g id="edge20" class="edge">
<title>Parameter880&#45;&gt;Plus112/Add (op#6)\n input0 Convolution110_Output_0\n input1 Parameter88\n output0 Plus112_Output_0</title>
<path fill="none" stroke="#000000" d="M2859.2016,-175.7784C2887.1379,-178.2099 2919.5615,-181.0319 2951.1621,-183.7823"/>
<polygon fill="#000000" stroke="#000000" points="2951.1205,-187.2918 2961.3864,-184.6722 2951.7275,-180.3182 2951.1205,-187.2918"/>
</g>
<!-- ReLU114_Output_00 -->
<g id="node24" class="node">
<title>ReLU114_Output_00</title>
<polygon fill="none" stroke="#000000" points="3985.9931,-188.5442 3985.9931,-203.4558 3920.7928,-214 3828.5857,-214 3763.3854,-203.4558 3763.3854,-188.5442 3828.5857,-178 3920.7928,-178 3985.9931,-188.5442"/>
<text text-anchor="middle" x="3874.6892" y="-192.3" font-family="Times,serif" font-size="14.00" fill="#000000">ReLU114_Output_0</text>
</g>
<!-- ReLU114/Relu (op#7)\n input0 Plus112_Output_0\n output0 ReLU114_Output_0&#45;&gt;ReLU114_Output_00 -->
<g id="edge22" class="edge">
<title>ReLU114/Relu (op#7)\n input0 Plus112_Output_0\n output0 ReLU114_Output_0&#45;&gt;ReLU114_Output_00</title>
<path fill="none" stroke="#000000" d="M3727.6979,-196C3736.0616,-196 3744.5239,-196 3752.942,-196"/>
<polygon fill="#000000" stroke="#000000" points="3753.1787,-199.5001 3763.1787,-196 3753.1786,-192.5001 3753.1787,-199.5001"/>
</g>
<!-- Pooling160/MaxPool (op#8)\n input0 ReLU114_Output_0\n output0 Pooling160_Output_0 -->
<g id="node25" class="node">
<title>Pooling160/MaxPool (op#8)\n input0 ReLU114_Output_0\n output0 Pooling160_Output_0</title>
<polygon fill="#0f9d58" stroke="#0f9d58" points="4257.841,-222.5 4021.841,-222.5 4021.841,-169.5 4257.841,-169.5 4257.841,-222.5"/>
<text text-anchor="middle" x="4139.841" y="-207.3" font-family="Times,serif" font-size="14.00" fill="#ffffff">Pooling160/MaxPool (op#8)</text>
<text text-anchor="middle" x="4139.841" y="-192.3" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input0 ReLU114_Output_0</text>
<text text-anchor="middle" x="4139.841" y="-177.3" font-family="Times,serif" font-size="14.00" fill="#ffffff"> output0 Pooling160_Output_0</text>
</g>
<!-- ReLU114_Output_00&#45;&gt;Pooling160/MaxPool (op#8)\n input0 ReLU114_Output_0\n output0 Pooling160_Output_0 -->
<g id="edge23" class="edge">
<title>ReLU114_Output_00&#45;&gt;Pooling160/MaxPool (op#8)\n input0 ReLU114_Output_0\n output0 Pooling160_Output_0</title>
<path fill="none" stroke="#000000" d="M3985.985,-196C3994.4396,-196 4003.0127,-196 4011.562,-196"/>
<polygon fill="#000000" stroke="#000000" points="4011.5787,-199.5001 4021.5787,-196 4011.5787,-192.5001 4011.5787,-199.5001"/>
</g>
<!-- Pooling160_Output_00 -->
<g id="node26" class="node">
<title>Pooling160_Output_00</title>
<polygon fill="none" stroke="#000000" points="4621.341,-188.5442 4621.341,-203.4558 4550.7538,-214 4450.9283,-214 4380.341,-203.4558 4380.341,-188.5442 4450.9283,-178 4550.7538,-178 4621.341,-188.5442"/>
<text text-anchor="middle" x="4500.841" y="-192.3" font-family="Times,serif" font-size="14.00" fill="#000000">Pooling160_Output_0</text>
</g>
<!-- Pooling160/MaxPool (op#8)\n input0 ReLU114_Output_0\n output0 Pooling160_Output_0&#45;&gt;Pooling160_Output_00 -->
<g id="edge24" class="edge">
<title>Pooling160/MaxPool (op#8)\n input0 ReLU114_Output_0\n output0 Pooling160_Output_0&#45;&gt;Pooling160_Output_00</title>
<path fill="none" stroke="#000000" d="M4258.0459,-196C4293.8522,-196 4333.3862,-196 4369.9709,-196"/>
<polygon fill="#000000" stroke="#000000" points="4370.2059,-199.5001 4380.2059,-196 4370.2059,-192.5001 4370.2059,-199.5001"/>
</g>
<!-- Times212_reshape0/Reshape (op#9)\n input0 Pooling160_Output_0\n input1 Pooling160_Output_0_reshape0_shape\n output0 Pooling160_Output_0_reshape0 -->
<g id="node27" class="node">
<title>Times212_reshape0/Reshape (op#9)\n input0 Pooling160_Output_0\n input1 Pooling160_Output_0_reshape0_shape\n output0 Pooling160_Output_0_reshape0</title>
<polygon fill="#0f9d58" stroke="#0f9d58" points="5093.841,-184 4743.841,-184 4743.841,-116 5093.841,-116 5093.841,-184"/>
<text text-anchor="middle" x="4918.841" y="-168.8" font-family="Times,serif" font-size="14.00" fill="#ffffff">Times212_reshape0/Reshape (op#9)</text>
<text text-anchor="middle" x="4918.841" y="-153.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input0 Pooling160_Output_0</text>
<text text-anchor="middle" x="4918.841" y="-138.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input1 Pooling160_Output_0_reshape0_shape</text>
<text text-anchor="middle" x="4918.841" y="-123.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> output0 Pooling160_Output_0_reshape0</text>
</g>
<!-- Pooling160_Output_00&#45;&gt;Times212_reshape0/Reshape (op#9)\n input0 Pooling160_Output_0\n input1 Pooling160_Output_0_reshape0_shape\n output0 Pooling160_Output_0_reshape0 -->
<g id="edge25" class="edge">
<title>Pooling160_Output_00&#45;&gt;Times212_reshape0/Reshape (op#9)\n input0 Pooling160_Output_0\n input1 Pooling160_Output_0_reshape0_shape\n output0 Pooling160_Output_0_reshape0</title>
<path fill="none" stroke="#000000" d="M4599.1076,-185.186C4639.2412,-180.7694 4687.0344,-175.5098 4733.2775,-170.4209"/>
<polygon fill="#000000" stroke="#000000" points="4733.8711,-173.8768 4743.4282,-169.3038 4733.1053,-166.9188 4733.8711,-173.8768"/>
</g>
<!-- Pooling160_Output_0_reshape00 -->
<g id="node28" class="node">
<title>Pooling160_Output_0_reshape00</title>
<polygon fill="none" stroke="#000000" points="5474.841,-134.5442 5474.841,-149.4558 5373.7929,-160 5230.8892,-160 5129.841,-149.4558 5129.841,-134.5442 5230.8892,-124 5373.7929,-124 5474.841,-134.5442"/>
<text text-anchor="middle" x="5302.341" y="-138.3" font-family="Times,serif" font-size="14.00" fill="#000000">Pooling160_Output_0_reshape0</text>
</g>
<!-- Times212_reshape0/Reshape (op#9)\n input0 Pooling160_Output_0\n input1 Pooling160_Output_0_reshape0_shape\n output0 Pooling160_Output_0_reshape0&#45;&gt;Pooling160_Output_0_reshape00 -->
<g id="edge26" class="edge">
<title>Times212_reshape0/Reshape (op#9)\n input0 Pooling160_Output_0\n input1 Pooling160_Output_0_reshape0_shape\n output0 Pooling160_Output_0_reshape0&#45;&gt;Pooling160_Output_0_reshape00</title>
<path fill="none" stroke="#000000" d="M5094.0372,-146.3453C5102.5496,-146.1677 5111.1058,-145.9893 5119.638,-145.8113"/>
<polygon fill="#000000" stroke="#000000" points="5119.7142,-149.3105 5129.639,-145.6026 5119.5682,-142.3121 5119.7142,-149.3105"/>
</g>
<!-- Pooling160_Output_0_reshape00&#45;&gt;Times212/MatMul (op#10)\n input0 Pooling160_Output_0_reshape0\n input1 Parameter193_reshape1\n output0 Times212_Output_0 -->
<g id="edge28" class="edge">
<title>Pooling160_Output_0_reshape00&#45;&gt;Times212/MatMul (op#10)\n input0 Pooling160_Output_0_reshape0\n input1 Parameter193_reshape1\n output0 Times212_Output_0</title>
<path fill="none" stroke="#000000" d="M5428.4826,-129.6849C5451.7912,-127.4093 5476.4167,-125.0052 5500.577,-122.6464"/>
<polygon fill="#000000" stroke="#000000" points="5500.9195,-126.1297 5510.5321,-121.6745 5500.2393,-119.1628 5500.9195,-126.1297"/>
</g>
<!-- Pooling160_Output_0_reshape0_shape0 -->
<g id="node29" class="node">
<title>Pooling160_Output_0_reshape0_shape0</title>
<polygon fill="none" stroke="#000000" points="4707.841,-134.5442 4707.841,-149.4558 4586.5833,-160 4415.0988,-160 4293.841,-149.4558 4293.841,-134.5442 4415.0988,-124 4586.5833,-124 4707.841,-134.5442"/>
<text text-anchor="middle" x="4500.841" y="-138.3" font-family="Times,serif" font-size="14.00" fill="#000000">Pooling160_Output_0_reshape0_shape</text>
</g>
<!-- Pooling160_Output_0_reshape0_shape0&#45;&gt;Times212_reshape0/Reshape (op#9)\n input0 Pooling160_Output_0\n input1 Pooling160_Output_0_reshape0_shape\n output0 Pooling160_Output_0_reshape0 -->
<g id="edge27" class="edge">
<title>Pooling160_Output_0_reshape0_shape0&#45;&gt;Times212_reshape0/Reshape (op#9)\n input0 Pooling160_Output_0\n input1 Pooling160_Output_0_reshape0_shape\n output0 Pooling160_Output_0_reshape0</title>
<path fill="none" stroke="#000000" d="M4708.0042,-145.9648C4716.4692,-146.1269 4724.9382,-146.2889 4733.3557,-146.45"/>
<polygon fill="#000000" stroke="#000000" points="4733.5288,-149.9539 4743.5939,-146.646 4733.6628,-142.9552 4733.5288,-149.9539"/>
</g>
<!-- Plus214/Add (op#11)\n input0 Times212_Output_0\n input1 Parameter194\n output0 Plus214_Output_0 -->
<g id="node31" class="node">
<title>Plus214/Add (op#11)\n input0 Times212_Output_0\n input1 Parameter194\n output0 Plus214_Output_0</title>
<polygon fill="#0f9d58" stroke="#0f9d58" points="6328.841,-168 6110.841,-168 6110.841,-100 6328.841,-100 6328.841,-168"/>
<text text-anchor="middle" x="6219.841" y="-152.8" font-family="Times,serif" font-size="14.00" fill="#ffffff">Plus214/Add (op#11)</text>
<text text-anchor="middle" x="6219.841" y="-137.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input0 Times212_Output_0</text>
<text text-anchor="middle" x="6219.841" y="-122.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> input1 Parameter194</text>
<text text-anchor="middle" x="6219.841" y="-107.8" font-family="Times,serif" font-size="14.00" fill="#ffffff"> output0 Plus214_Output_0</text>
</g>
<!-- Times212_Output_00&#45;&gt;Plus214/Add (op#11)\n input0 Times212_Output_0\n input1 Parameter194\n output0 Plus214_Output_0 -->
<g id="edge30" class="edge">
<title>Times212_Output_00&#45;&gt;Plus214/Add (op#11)\n input0 Times212_Output_0\n input1 Parameter194\n output0 Plus214_Output_0</title>
<path fill="none" stroke="#000000" d="M6058.02,-117.1306C6071.8805,-118.5755 6086.2688,-120.0755 6100.4927,-121.5583"/>
<polygon fill="#000000" stroke="#000000" points="6100.502,-125.0781 6110.811,-122.6339 6101.2278,-118.1159 6100.502,-125.0781"/>
</g>
<!-- Plus214_Output_00 -->
<g id="node32" class="node">
<title>Plus214_Output_00</title>
<polygon fill="none" stroke="#000000" points="6574.841,-126.5442 6574.841,-141.4558 6513.3335,-152 6426.3486,-152 6364.841,-141.4558 6364.841,-126.5442 6426.3486,-116 6513.3335,-116 6574.841,-126.5442"/>
<text text-anchor="middle" x="6469.841" y="-130.3" font-family="Times,serif" font-size="14.00" fill="#000000">Plus214_Output_0</text>
</g>
<!-- Plus214/Add (op#11)\n input0 Times212_Output_0\n input1 Parameter194\n output0 Plus214_Output_0&#45;&gt;Plus214_Output_00 -->
<g id="edge31" class="edge">
<title>Plus214/Add (op#11)\n input0 Times212_Output_0\n input1 Parameter194\n output0 Plus214_Output_0&#45;&gt;Plus214_Output_00</title>
<path fill="none" stroke="#000000" d="M6329.131,-134C6337.5378,-134 6346.041,-134 6354.4851,-134"/>
<polygon fill="#000000" stroke="#000000" points="6354.7454,-137.5001 6364.7454,-134 6354.7453,-130.5001 6354.7454,-137.5001"/>
</g>
<!-- Parameter1940 -->
<g id="node33" class="node">
<title>Parameter1940</title>
<polygon fill="none" stroke="#000000" points="6044.7728,-153.5442 6044.7728,-168.4558 5995.6067,-179 5926.0754,-179 5876.9093,-168.4558 5876.9093,-153.5442 5926.0754,-143 5995.6067,-143 6044.7728,-153.5442"/>
<text text-anchor="middle" x="5960.841" y="-157.3" font-family="Times,serif" font-size="14.00" fill="#000000">Parameter194</text>
</g>
<!-- Parameter1940&#45;&gt;Plus214/Add (op#11)\n input0 Times212_Output_0\n input1 Parameter194\n output0 Plus214_Output_0 -->
<g id="edge32" class="edge">
<title>Parameter1940&#45;&gt;Plus214/Add (op#11)\n input0 Times212_Output_0\n input1 Parameter194\n output0 Plus214_Output_0</title>
<path fill="none" stroke="#000000" d="M6041.0165,-152.6419C6059.8264,-150.6811 6080.2684,-148.55 6100.3853,-146.4529"/>
<polygon fill="#000000" stroke="#000000" points="6100.9611,-149.9119 6110.5443,-145.3939 6100.2352,-142.9497 6100.9611,-149.9119"/>
</g>
</g>
</svg>
`;

export const SvgComponent : React.FunctionComponent = () => {
    //let svgPath = path.join()
    let parser = new DOMParser();
    var dom = parser.parseFromString(svgContent, "text/xml");
    var svg = dom.querySelector('svg');

    //let svgAsElement = React.createElement(svgContent);
    if (!svg) {
        return (<div>{`Testing with the embedded SVG string, checking svg: ${svg}.`}</div>);
    } else {
        // from https://github.com/vqdo/cat-maker/blob/30a607d6fa17c4fd5a91ad0a1d4687bb46a98986/src/components/cat-img.tsx
        return (<div dangerouslySetInnerHTML={{__html: svg.outerHTML}}></div>);
    }
}